# Generated by Django 4.0.6 on 2023-02-24 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='phone_number',
            field=models.CharField(default=1, max_length=17),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='tg_username',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
