# Generated by Django 4.0.6 on 2023-02-26 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_products_phone_number_products_tg_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='bio',
            new_name='body',
        ),
    ]
